[build]
target = "index.html"
dist = "dist"
release = false
public_url = "/youtube_radus-self-driving-car-tutorial-series/" # for {username}.github.io

[watch]
watch = ["index.html", "src/", "style/", "public/"]

[clean]
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "sh"
# run tailwind build with webpack
command_arguments = [
    "-c",
    "[ ! -d \"./node_modules\" ] && npm i || :; npm run build_css",
]
